### ISSUE TITLE
cl-ana libraries are broken

### ISSUE THREAD

**Issue by Uthar** [Uthar/nix-cl#12]
[cl-ana](https://github.com/ghollisjr/cl-ana) is a "Free (GPL) Common Lisp data analysis library with emphasis on modularity and conceptual clarity. "

Build is broken, can be repaired by this patch:

```patch
--- a/pkgs/development/lisp-modules-new/ql.nix
+++ b/pkgs/development/lisp-modules-new/ql.nix
@@ -127,6 +127,15 @@ let
       nativeLibs = [ libfixposix ];
       systems = [ "iolib" "iolib/os" "iolib/pathnames" ];
     };
+    "cl-ana.hdf-cffi" = pkg: {
+      nativeBuildInputs = [ hdf5 pkg-config ];
+      nativeLibs = [ hdf5 ];
+      NIX_LDFLAGS = [ "-lhdf5" ];
+    };
+    gsll = pkg: {
+      nativeBuildInputs = [ gsl ];
+      nativeLibs = [ gsl ];
+    };
   };
 
   qlpkgs =

```

**Comment by Uthar** [comment]
Fixes ~30 builds

**Comment by teu5us** [comment]
What version of hdf5 do you use here? I am testing my own implementation currently and hdf5 provided by nixpkgs did not work for me, so I settled with 1.10.5

**Comment by Uthar** [comment]
I am just using the one from nixpkgs
The version is 1.12.2

**Comment by Uthar** [comment]
the command will build it `nix build github:uthar/nixpkgs/fixes#legacyPackages.x86_64-linux.lispPackages_new.sbclPackages.cl-ana_dot_hdf-cffi`

**Comment by teu5us** [comment]
Interesting. I get groveler errors with this version and cl-ana from latest quicklisp

**Comment by Uthar** [comment]
What are the errors?

**Comment by Uthar** [comment]
fixed in tip of trunk https://github.com/Uthar/nix-cl/commit/0e1c4c28d43017545e55df7da52911b66a7f52c2
