### ISSUE TITLE
Quicklisp March 2022 Update

### ISSUE THREAD

**Issue by nagy** [Uthar/nix-cl#4]
Could we get an update to the March dist update of Quicklisp? If I am not mistaken, the last update in this repo is from December. Thanks.

http://blog.quicklisp.org/2022/04/march-2022-quicklisp-dist-update-now.html

**Comment by Uthar** [comment]
Updated now in trunk.

cl-protobuf stopped building, it seems that it now requires to compile a separate C++ program, which is not in nixpkgs. Maybe someone who wants to use it will fix it.

**Comment by nagy** [comment]
Thank you.
